<?php
/**
 * @package cart
 * @copyright Copyright 2003-2010 Zen Cart Development Team
 * @copyright Portions Copyright 2003 osCommerce
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @Version $id: Product Typ Auction 18 2010-06-20 10:30:40Z davewest $
*/

define('HEADING_AUCTION_HELP', '<h1>Auction Help</h1>');
define('TEXT_AUCTION_HELP', '<div><b>Reserve Price:</b> Minimum price that the product may sell for. May be the same as Starting Price or not used.</div><br /><div><b>Buy Now Price: </b>If available, the Buy Now Price allows you to buy an item when you want it, at a known set price.</div><br /><div><b>Minimum Bid Increase:</b> The minimum amount required to add to the current bid price. </div><br /><div><b>Starting Bid:</b> The starting price may be set for the auction. This may be less or the same as a reserve price. </div><br /><div><b>Auction Ends:</b> The date and time the Auction ends.</div><br /><div><b>Current Highest Bid:</b> The current highest bid on the product. If you are logged in, and you are the current highest bidder, it will say <strong>You are the current high bidder!</strong></div><br /><div><b>How to bid:</b> Once you find an item you\'re interested in, it\'s easy to place a bid.<ol><li>Carefully review the product listing, and click the Login to Place Bid button on the product page.</li><li>Enter the amount to bid on the item. If a minimum bid increase is active, you must enter the current bid plus at least the minimum amount for the bid increase.</li><li>Click the Submit button to place your bid. </li></ol><p><b>Important:</b> Please note, <font color="#FF0000">this is a traditional auction system</font> where the full amount of your submitted bid will be reflected immediately as current highest bid. Each bid you make is a binding contract to buy the item if you win. If you are the winning bidder on an item, you are obligated to purchase that item.<p><b>If you make a mistake:</b> Please notify us immediately to cancel your bid.<p>You\'ll get an email if you have been outbid when another buyer has placed a higher bid than yours, and you are no longer the current high bidder. And when the auction ends, you\'ll receive another email indicating whether you\'ve won the product or not, with an explanation of what you can do next.</p></div>');
define('TEXT_CLOSE_AUCTION_HELP_WINDOW', '<u>Close Window</u> [x]');
?>